wamv_camera:
    - name: middle_camera
      x: 0.75
      y: 0
      P: ${radians(15)}
    - name: left_camera
      x: 0.75
      y: 0.2
      P: ${radians(15)}
    - name: right_camera
      x: 0.75
      y: -0.2
      P: ${radians(15)}
wamv_gps:
    - name: gps_wamv
      x: -0.85
      y: 0
      z: 1.3
wamv_imu:
    - name: imu_wamv
      y: 0
wamv_p3d:
    - name: p3d_wamv
lidar:
    - name: velodyne_front
